// <auto-generated />
using System;
using DataRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataRepository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191101125932_Data2")]
    partial class Data2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DataRepository.DbEntities.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("RegionId");

                    b.HasKey("CityId");

                    b.HasIndex("RegionId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("DataRepository.DbEntities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("DataRepository.DbEntities.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<Guid?>("PortfolioProjectId");

                    b.HasKey("ImageId");

                    b.HasIndex("PortfolioProjectId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("DataRepository.DbEntities.PortfolioProject", b =>
                {
                    b.Property<Guid>("PortfolioProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<Guid>("WorkerId");

                    b.HasKey("PortfolioProjectId");

                    b.HasIndex("WorkerId");

                    b.ToTable("PortfolioProjects");
                });

            modelBuilder.Entity("DataRepository.DbEntities.Region", b =>
                {
                    b.Property<Guid>("RegionId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CountryId");

                    b.Property<string>("Name");

                    b.HasKey("RegionId");

                    b.HasIndex("CountryId");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("DataRepository.DbEntities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("WorkerTypeId");

                    b.HasKey("ServiceId");

                    b.HasIndex("WorkerTypeId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkGeography", b =>
                {
                    b.Property<Guid>("WorkGeographyId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CityId");

                    b.Property<Guid?>("CountryId");

                    b.Property<Guid?>("RegionId");

                    b.Property<Guid?>("WorkerId");

                    b.HasKey("WorkGeographyId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("RegionId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkGeography");
                });

            modelBuilder.Entity("DataRepository.DbEntities.Worker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<string>("ContactInfo");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<int>("WorkerTypeId");

                    b.HasKey("WorkerId");

                    b.HasIndex("WorkerTypeId");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            WorkerId = new Guid("504b2100-0b85-4a03-8def-8a856a3db6d5"),
                            ContactInfo = "{\"address\":\"Ломоносова 50\",\"email\":\"verandadesignstuio@gmail.com\",\"phones\":[\"+1111111111\",\"222222222222\"],\"site\":\"verandadesignstuion.com\",\"socialMedia\":{\"instagram\":\"instagramVeranda\",\"facebook\":\"facebookVeranda\",\"pinterest\":\"pinterestVeranda\"}}",
                            Name = "Veranda Design Studio",
                            Rating = 0,
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkerTypeId = 1
                        });
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkerCity", b =>
                {
                    b.Property<Guid>("WorkerCityId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CityId");

                    b.Property<Guid>("WorkerId");

                    b.HasKey("WorkerCityId");

                    b.HasIndex("CityId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerCity");
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkerPrice", b =>
                {
                    b.Property<Guid>("WorkerPriceId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("WorkerId");

                    b.HasKey("WorkerPriceId");

                    b.HasIndex("WorkerId")
                        .IsUnique();

                    b.ToTable("WorkerPrice");

                    b.HasData(
                        new
                        {
                            WorkerPriceId = new Guid("785cc532-d321-4a31-a5f1-a7feb57ef209"),
                            Amount = 10m,
                            WorkerId = new Guid("504b2100-0b85-4a03-8def-8a856a3db6d5")
                        });
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkerService", b =>
                {
                    b.Property<Guid>("WorkerServiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ServiceId");

                    b.Property<Guid>("WorkerId");

                    b.HasKey("WorkerServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerService");
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkerType", b =>
                {
                    b.Property<int>("WorkerTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("WorkerTypeId");

                    b.ToTable("WorkerType");

                    b.HasData(
                        new
                        {
                            WorkerTypeId = 1,
                            Name = "Дизайнер"
                        },
                        new
                        {
                            WorkerTypeId = 2,
                            Name = "Чертежник"
                        },
                        new
                        {
                            WorkerTypeId = 3,
                            Name = "Архитектор"
                        });
                });

            modelBuilder.Entity("DataRepository.DbEntities.City", b =>
                {
                    b.HasOne("DataRepository.DbEntities.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("DataRepository.DbEntities.Image", b =>
                {
                    b.HasOne("DataRepository.DbEntities.PortfolioProject", "PortfolioProject")
                        .WithMany("Images")
                        .HasForeignKey("PortfolioProjectId");
                });

            modelBuilder.Entity("DataRepository.DbEntities.PortfolioProject", b =>
                {
                    b.HasOne("DataRepository.DbEntities.Worker", "Worker")
                        .WithMany("PortfolioProjects")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataRepository.DbEntities.Region", b =>
                {
                    b.HasOne("DataRepository.DbEntities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("DataRepository.DbEntities.Service", b =>
                {
                    b.HasOne("DataRepository.DbEntities.WorkerType", "WorkerType")
                        .WithMany("Services")
                        .HasForeignKey("WorkerTypeId");
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkGeography", b =>
                {
                    b.HasOne("DataRepository.DbEntities.City", "City")
                        .WithMany("WorkGeographies")
                        .HasForeignKey("CityId");

                    b.HasOne("DataRepository.DbEntities.Country", "Country")
                        .WithMany("WorkGeographies")
                        .HasForeignKey("CountryId");

                    b.HasOne("DataRepository.DbEntities.Region", "Region")
                        .WithMany("WorkGeographies")
                        .HasForeignKey("RegionId");

                    b.HasOne("DataRepository.DbEntities.Worker", "Worker")
                        .WithMany("WorkGeographies")
                        .HasForeignKey("WorkerId");
                });

            modelBuilder.Entity("DataRepository.DbEntities.Worker", b =>
                {
                    b.HasOne("DataRepository.DbEntities.WorkerType", "WorkerType")
                        .WithMany()
                        .HasForeignKey("WorkerTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkerCity", b =>
                {
                    b.HasOne("DataRepository.DbEntities.City", "City")
                        .WithMany("WorkerCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataRepository.DbEntities.Worker", "Worker")
                        .WithMany("WorkerCities")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkerPrice", b =>
                {
                    b.HasOne("DataRepository.DbEntities.Worker", "Worker")
                        .WithOne("WorkerPrice")
                        .HasForeignKey("DataRepository.DbEntities.WorkerPrice", "WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataRepository.DbEntities.WorkerService", b =>
                {
                    b.HasOne("DataRepository.DbEntities.Service", "Service")
                        .WithMany("WorkerServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataRepository.DbEntities.Worker", "Worker")
                        .WithMany("WorkerServices")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
